### ISSUE TITLE
Populating data

### ISSUE THREAD

**Issue by wakaguaka** [simonray/bootstrap-table.mvc#1]
Hello,
How can I show data that belongs from other class in bootstrap-table?
For example:

 public class Person
    {
        public int PersonId { get; set; }
        public string Name { get; set; }
        public Family FamilyItem { get; set; }
    }
    public class Family
    {
        public int FamilyId { get; set; }
        public string Name { get; set; }
    }

Applying @Html.BootstrapTable<Person> will show me "[object Object]" for FamilyItem.
How can I flatten to "FamilyItem.Name" ?

**Comment by simonray** [comment]
You could try -
- Hide the child object using an annotation
- Add a new derived property (get) to your model. 

``` csharp
public class Person
{
  public int PersonId { get; set; }
  public string Name { get; set; }

  [Display(AutoGenerateField = false)]
  public Family FamilyItem { get; set; }

  public string FamilyName { 
    get { 
      return FamilyItem.Name;
    }
  }
}
```
